/** Copia de src/data/questionIds.ts */
export const EXTRA_IDS = {
  champion: 'extra_champion',
  runnerUp: 'extra_runner_up',
  thirdPlace: 'extra_third_place',
  fourthPlace: 'extra_fourth_place',
  topScorer: 'extra_top_scorer',
} as const

export const BONUS_QUESTION_IDS = [
  'q_offense_most_goals_total',
  'q_offense_most_goals_group',
  'q_offense_most_goals_single_match',
  'q_offense_most_lopsided_score',
  'q_offense_over_5_goals',
  'q_offense_best_goal_average',
  'q_defense_least_conceded',
  'q_defense_most_conceded',
  'q_defense_most_clean_sheets',
  'q_stats_most_corners_match',
  'q_stats_most_fouls_match',
  'q_stats_most_penalties_match',
  'q_stats_penalties_total_range',
  'q_stats_total_goals_range',
  'q_discipline_most_yellows',
  'q_discipline_most_reds',
  'q_discipline_red_in_final',
  'q_discipline_first_yellow_player',
  'q_players_top_assists',
  'q_players_hat_trick',
  'q_players_first_goal',
  'q_events_goals_extra_time',
  'q_events_penalty_shootout_final',
  'q_team_surprise',
  'q_team_favorite_out_first',
  'q_team_last_in_group',
  'q_group_most_goals_total',
  'q_fun_own_goals',
  'q_fun_own_goals_count',
  'q_fun_most_repeated_scoreline',
] as const
